// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOYRXJUybHlH00XMvHlJJMa80r2RMBf4',
    appId: '1:877604661855:android:6bd72a8cd713ce44a689ea',
    messagingSenderId: '877604661855',
    projectId: 'eaty-63ab7',
    storageBucket: 'eaty-63ab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNAcuekfKIvUx_JzGxJr2LysE5RvElOQ',
    appId: '1:877604661855:ios:95d6d59b2271f9a8a689ea',
    messagingSenderId: '877604661855',
    projectId: 'eaty-63ab7',
    storageBucket: 'eaty-63ab7.firebasestorage.app',
    androidClientId: '877604661855-52k3tk2rnrfqcqvb0j751ccqdfo0166k.apps.googleusercontent.com',
    iosClientId: '877604661855-ra53kpt0suqtroa7ilkklusdq1iidu2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatyy',
  );
}
